#!/bin/bash
if [[ "$1" = "--yeah" ]]; then
    exit_code=0
elif [[ "$1" = "--nope" ]]; then
    exit_code=1
else
    # Run the command and capture its exit code
    "$@"
    exit_code=$?
fi

# depending on the platform, choose the right sound command
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    player=afplay
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux
    player='aplay -q'
else
# no windows for now.
    player=echo # placeholder
fi

SUCCESS_SOUND=sounds/classic-bike-bell-distorted-double-1.wav
ERROR_SOUND=sounds/bottlefullmute-1.wav

if [ $exit_code -eq 0 ]; then
    $player $SUCCESS_SOUND &
else
    $player $ERROR_SOUND &
fi

# Exit with the same code as the original command
exit $exit_code
